version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.7.5

    working_directory: ~/ner-project

    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            sudo apt update
            pip install -r requirements.txt
            pip install -r requirements_dev.txt
      - run:
          name: enforce styleguide
          command: |
            . venv/bin/activate
            flake8 ner
